### ISSUE TITLE
Invalid PURL in generated SPDX

### ISSUE THREAD

**Issue by pombredanne** [spdx/spdx-gradle-plugin#100]
Hi!
in ...
`"referenceLocator" : "pkg://maven/org.apache.logging.log4j/log4j-core@2.18.0",`
the PURL is not correct. It should be instead:
`pkg:maven/org.apache.logging.log4j/log4j-core@2.18.0`
using `pkg://` is not valid because there is no URI/URL host/port/authority in a PURL.

**Comment by pombredanne** [comment]
See also https://github.com/spdx/spdx-gradle-plugin/blob/801c780e43562dadfeb0a9efb9525c4da46d7d6e/example.spdx.json#L51

**Comment by pombredanne** [comment]
May I suggest that you also use a PURL for the package name and not introduce yet another naming scheme (which is Gradle-specific)
So rather than:
```
    "name" : "com.google.code.gson:gson:2.8.9" 
```
Consider
```
    "name" : "pkg:maven/com.google.code.gson/gson@2.8.9"
```

.... this will help users.

**Comment by goneall** [comment]
I'm a supporter of purls, but I would suggest not using the purl format for the name.

Using purls as external references are definitely encouraged, and it looks like this Gradle plugin has this covered.

The spec describes the [name field](https://spdx.github.io/spdx-spec/v2.3/package-information/#71-package-name-field) as `Identify the full name of the package as given by the Package Originator`, so it should follow the conventions of the originator of the package.

For the Maven plugin, by default, we take it from the `<name>` element of the pom file.  There is also an [option](https://spdx.github.io/spdx-maven-plugin/createSPDX-mojo.html#useArtifactID) to override the name to be the `groupId:artifactId`.

**Comment by loosebazooka** [comment]
so name should not include "version" then?

**Comment by goneall** [comment]
> so name should not include "version" then?

There is a separate [package version field](https://spdx.github.io/spdx-spec/v2.3/package-information/#73-package-version-field).

**Comment by pombredanne** [comment]
re: 

>For the Maven plugin, by default, we take it from the <name> element of the pom file. There is also an option to override the name to be the groupId:artifactId.

Using multiple alternative, non-structured, ecosystem-specific, and undocumented naming convention is no great IMHO as it makes the name essentially a useless field.

Using a PURL for a name as done here by @loosebazooka is actually rather nice and brings SPDX closer to other tools using PURL and makes the name actually useful.

**Comment by loosebazooka** [comment]
I don't think I'm using purl for name though here. Only download location.

**Comment by pombredanne** [comment]
> I don't think I'm using purl for name though here. Only download location.

My bad! I was looking at the wrong stuff ... ignore the noise!

**Comment by loosebazooka** [comment]
I think this can be closed
