### ISSUE TITLE
Running the spdx plugin as a gradle init script

### ISSUE THREAD

**Issue by mpermar** [spdx/spdx-gradle-plugin#107]
Hi, this might be a non issue, but I couldn't figure out how to do this. 

With the [cyclonedx gradle plugin](https://github.com/CycloneDX/cyclonedx-gradle-plugin), I can take some gradle project, e.g. [spring-petclinic](https://github.com/spring-projects/spring-petclinic) and get an SBOM running the following:

```console
tee -a init.gradle <<EOF
initscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "org.cyclonedx:cyclonedx-gradle-plugin:1.8.2"
  }
}

allprojects{
  apply plugin:org.cyclonedx.gradle.CycloneDxPlugin
  cyclonedxBom {
    projectType = "application"
    schemaVersion = "1.5"
    destination = file("build/reports")
    outputName = "bom"
    outputFormat = "json"
    includeBomSerialNumber = false
    includeLicenseText = true
    componentVersion = "2.0.0"
  }
EOF

./gradlew --init-script init.cyclonedx.gradle cyclonedxBom -info
``` 

Is this something that can be done or supported in this SPDX plugin?

Thanks!

**Comment by mpermar** [comment]
My tests are probably invalid as I am just a basic gradle user. Just picked up the code at the [gradle plugins](https://plugins.gradle.org/plugin/org.spdx.sbom) website, replace `buildscript` with `initscript` and run. So, literally nothing. 

Does this plugin support being run as an init script?

**Comment by vajain-1982** [comment]
@mpermar , below init script worked 
initscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "org.spdx:spdx-gradle-plugin:0.6.0"
  }
}

allprojects {
  apply plugin: org.spdx.sbom.gradle.SpdxSbomPlugin
  spdxSbom {
    targets {
      create("spring") {
  // configure
      }
    }
  }
}

 ./gradlew -I init.gradle spdxSbom

**Comment by vajain-1982** [comment]
@loosebazooka , Is there a way overwrite the properties of "SpdxSbomTask" like outputfile or outputdirectory ?

**Comment by loosebazooka** [comment]
There isn't a great way, but https://github.com/spdx/spdx-gradle-plugin/pull/112 should make it much easier

**Comment by loosebazooka** [comment]
try the outputFile extension option in 0.7.0 release of the plugin: you can see instructions here: https://github.com/spdx/spdx-gradle-plugin/pull/113/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R78

**Comment by vajain-1982** [comment]
@loosebazooka , 
Your fix will enable to change the file name on "project/build/spdx/" location , which I was able to work round by passing "project.name" in create.
The issue/support I was looking more like changing the location or dir for output spdx ( consider a multiple project repo ) , workaround would be find all spdx and copy to the output location.
something if i can set the outputFile as below , currently input is gradle's Regularfile.
````
initscript {
    repositories {
        mavenLocal()
        mavenCentral()
    }
    dependencies {
        classpath "org.spdx:spdx-gradle-plugin:0.7.0"
    }
}

allprojects {
    apply plugin: org.spdx.sbom.gradle.SpdxSbomPlugin
    spdxSbom {
        targets {
            create(project.name) {
             outputFile.set("/tmp/sbom/"+project.name+"-spdx.json")
            }
        }
    }
}

````

**Comment by loosebazooka** [comment]
I'm going to close this for now.
