### ISSUE TITLE
update dependencies to only signed versions

### ISSUE THREAD

**Issue by mathjeff** [spdx/spdx-gradle-plugin#14]
It could be nice to update the versions of the dependencies of this plugin to only signed versions to make it easier for dependent Gradle builds to establish trust for this plugin and its dependencies

Based on [this signature file change in AndroidX](https://r.android.com/c/platform/frameworks/support/+/2538151/18/gradle/verification-metadata.xml) it looks like the only unsigned dependency is `aopialliance:aopalliance:1.0`

Since the latest version of aopalliance seems to have been uploaded to Maven Central in 2015 ( https://mvnrepository.com/artifact/aopalliance/aopalliance ), I think that means that either this issue is infeasible or that this issue entails migrating to a different dependency than aopalliance

**Comment by loosebazooka** [comment]
Lemme add dependabot to this repo too. I think that maven-core dep that brings in aopalliance might be trimmable.
