### ISSUE TITLE
SPDXParser.OnlyUseLocalLicenses=true by default

### ISSUE THREAD

**Issue by mathjeff** [spdx/spdx-gradle-plugin#16]
As of https://github.com/spdx/spdx-gradle-plugin/commit/431fbe010da1f514edfb57dace9458da90a15650 , there's an embedded licenses file that this plugin uses to allow recognizing licenses without having to make a network request

However, running this plugin with network disabled still causes the Spdx-Java-Library plugin to [make a network request](https://github.com/spdx/Spdx-Java-Library/commit/359541574ff5e107919ec971c3c41e0455d3dc2f#diff-8c72e5ced8a299c7f6ac2ecae489c8c96c07e0d124094483494c66e299d11b79L106) unless SPDXParser.OnlyUseLocalLicenses or OnlyUseLocalLicenses is [set to false](https://github.com/spdx/Spdx-Java-Library/commit/32ef48f802341a92a24bdc5dcce2e2a91b6513ed#diff-8c72e5ced8a299c7f6ac2ecae489c8c96c07e0d124094483494c66e299d11b79R62)

It would be neat if the spdx-gradle-plugin could set this by default

**Comment by loosebazooka** [comment]
I think once/if this change is accepted, we can move forward with this.
