### ISSUE TITLE
Make spdx task be UP-TO-DATE after running once

### ISSUE THREAD

**Issue by mathjeff** [spdx/spdx-gradle-plugin#18]
In https://r.android.com/2538151 when we try to enable this plugin in AndroidX we're finding that if we run `./gradlew spdxSbomForRelease` twice in a row, in the second invocation the tasks aren't all UP-TO-DATE; the output says:

```
org.gradle.api.GradleException: Ran two consecutive builds of the same tasks, and in the second build, observed:
task :annotation:annotation-experimental:spdxSbomForRelease not UP-TO-DATE. It was out-of-date because:
[Value of input property 'documentInfo' has changed for task ':annotation:annotation-experimental:spdxSbomForRelease']
at androidx.build.uptodatedness.TaskUpToDateValidator.onFinish(TaskUpToDateValidator.kt:200)

BUILD FAILED in 32s
```

If possible it would be nice to make `spdxSbomForRelease be UP-TO-DATE` after running once

**Comment by loosebazooka** [comment]
Hrmm... I wonder what we are changing in document info? Also we probably need to apply the taskExtension at configuration time or something to really do UP-TO-DATE correctly.

**Comment by loosebazooka** [comment]
I'm not sure if this is still happening but #86 seems to fix the up-to-date check on the plugin repo itself

**Comment by loosebazooka** [comment]
I think UP-TO-DATE works now.
