### ISSUE TITLE
ResolvedComponentResultInternal behavior change breaks the plugin on the recent gradle.

### ISSUE THREAD

**Issue by AlexanderYukhanov** [spdx/spdx-gradle-plugin#24]
Now ResolvedComponentResultInternal.getRepositoryName() returns repository id instead of the repository name (see https://github.com/gradle/gradle/blob/51847e4a34e332f93029bb4b87520586948df120/subprojects/dependency-management/src/testFixtures/groovy/org/gradle/api/internal/artifacts/result/ResolutionResultDataBuilder.groovy#L48). 

Sure, that's a strange change in behavior, but it's internal api which is not expected to have a stable interface. Let's find other way to map the artifact to the repository?

**Comment by AlexanderYukhanov** [comment]
The problem is resolved with gradle-8.3-20230511225831+0000-bin.zip. Would still suggest to tack https://github.com/gradle/gradle/issues/9763 and remove the dependency on the internal API as soon as it resolved

**Comment by eygraber** [comment]
This should be fixed with https://github.com/spdx/spdx-gradle-plugin/pull/30
