### ISSUE TITLE
Avoid calling project.getRootProject().getAllprojects() in each project

### ISSUE THREAD

**Issue by liutikas** [spdx/spdx-gradle-plugin#25]
If `SpdxSbomPlugin` calls  [`project.getRootProject().getAllprojects() `](https://github.com/spdx/spdx-gradle-plugin/blob/2865aec0e398402c7a07af2f5a30ec1a2a75d8d4/src/main/java/org/spdx/sbom/gradle/SpdxSbomPlugin.java#LL108C17-L108C17) for every project the plugin is applied to. In a large codebase that means a N number of calls for N number of projects. This is very costly, for example in AndroidX project, we spend 1.5s just calling `getAllProjects()`.

A screenshot from a trace:
![image](https://github.com/spdx/spdx-gradle-plugin/assets/1418185/f28a3364-0473-4284-b473-0ca3cadca541)

It would be much better if all this work was moved to a [Shared Build Service](https://docs.gradle.org/current/userguide/build_services.html) so it can be computed once and then reused between projects.

**Comment by mathjeff** [comment]
Good idea - thanks for finding this!

**Comment by loosebazooka** [comment]
So I this is probably not going to be allowed anyway in the future with project isolation. But we can convert to a shared build service for now?

**Comment by loosebazooka** [comment]
Hopefully we can actually just use the ProjectComponentIdentifier to do this, but we need an update at gradle to make it so: https://github.com/gradle/gradle/issues/26737

**Comment by loosebazooka** [comment]
fixed by #60
