### ISSUE TITLE
Do we want to support the possibility of a `developer` that has an `organization`?

### ISSUE THREAD

**Issue by loosebazooka** [spdx/spdx-gradle-plugin#38]
Do we want to support the possibility of a `developer` that has an `organization`?

I think an example is:

https://repo1.maven.org/maven2/org/jetbrains/annotations/13.0/annotations-13.0.pom

which contains the text:

```
<developers>
<developer>
<id>JetBrains</id>
<name>JetBrains Team</name>
<organization>JetBrains</organization>
<organizationUrl>http://www.jetbrains.com</organizationUrl>
</developer>
</developers>
```

which is think is causing this text to appear in the sbom:

“supplier" : "Person: Kotlin Team"

maybe it would be better to output this text instead:

“supplier" : "Organization: JetBrains"

_Originally posted by @mathjeff in https://github.com/spdx/spdx-gradle-plugin/pull/29#discussion_r1307635106_

**Comment by eygraber** [comment]
So the order of resolution would be:

1. Organization
2. Organization nested under developer
3. Developer

What is there are multiple developers with different organizations?

**Comment by loosebazooka** [comment]
Cardinality of this value is "1..1", so I guess we have to have an arbitrary heuristic for this. How about:
1. Organization
2. First developer of `developers`
   a. If only contains organization then: `organization`
   b. else `developerName (email)`

**Comment by eygraber** [comment]
Following that heuristic, `JetBrains Team` would be used as the supplier for the example given above. 

Maybe:

1. Organization
2. First developer of `developers`
-> "organization" if organization is the same for all developers
-> "name (email if present, organization if present)"

**Comment by loosebazooka** [comment]
I don't think we're going to get a perfect mapping of this data. I think your suggestion is probably fine. Except it looks more like (if I'm not mistaken):

1. Organization
2. Developers:
    a. "organization" if organization is the same for all developers
    b. first developer of developers 
          - "name (email if present, organization if present)"
          - "organization" (if no email or name)

**Comment by loosebazooka** [comment]
@mathjeff I believe this will provide an experience that is compatible with your issue?

**Comment by mathjeff** [comment]
I think so!

**Comment by eygraber** [comment]
I should be able to get to it within the next week.

**Comment by loosebazooka** [comment]
Thanks, I'll assign it to you for now, but feel free to delegate to someone else if you have other obligations

**Comment by AlexanderYukhanov** [comment]
Can we generate a warning for cases when there are multiple developers to let the users to review the final result? And I think it may be welcome to have a configuration which would allow overriding of the supplier selection
