### ISSUE TITLE
Android App Versions not dedected 

### ISSUE THREAD

**Issue by PeterHasse** [spdx/spdx-gradle-plugin#79]
Running SPDX sbooms on an android project results in the following warning

```
spdx sboms require a version but project: app has no specified version
```

I guess this is again an android thing, the version is part of the gradle file and can be found in:

```
android {
    defaultConfig {
        applicationId "XYZ"
        minSdk 29
        targetSdk 34
        versionCode 1
        versionName "1.0"
```

_Originally posted by @PeterHasse in https://github.com/spdx/spdx-gradle-plugin/issues/49#issuecomment-1845251229_

**Comment by loosebazooka** [comment]
are android dependencies the same? Or is just the root project. If you had an android aar dependency, does it look the same? I wondering how deep into subproject parsing we need to go

**Comment by PeterHasse** [comment]
The project gradle file does not include the the version, only the app level gradle file. I'm note aware if there are projects with more than one app but i guess they will always be on the 2. level.

**Comment by loosebazooka** [comment]
Presumably you're generating sboms off the app level gradle file though?

**Comment by PeterHasse** [comment]
correct
